// This file will be generated by `supabase gen types typescript --local > src/types/db.ts`
// For now, we'll define a minimal structure.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      agents: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          initial_prompt: string;
          persona_config: Json | null;
          status: string | null;
          api_key: string;
          owner_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          initial_prompt: string;
          persona_config?: Json | null;
          status?: string | null;
          api_key: string;
          owner_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          initial_prompt?: string;
          persona_config?: Json | null;
          status?: string | null;
          api_key?: string;
          owner_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      knowledge_bases: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          content_type: string | null;
          content_data: string | null;
          status: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          content_type?: string | null;
          content_data?: string | null;
          status?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          content_type?: string | null;
          content_data?: string | null;
          status?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      agent_knowledge_bases: {
        Row: {
          agent_id: string;
          knowledge_base_id: string;
          priority: number | null;
        };
        Insert: {
          agent_id: string;
          knowledge_base_id: string;
          priority?: number | null;
        };
        Update: {
          agent_id?: string;
          knowledge_base_id?: string;
          priority?: number | null;
        };
        Relationships: [
          { foreignKeyName: "agent_knowledge_bases_agent_id_fkey"; columns: ["agent_id"]; referencedRelation: "agents"; referencedColumns: ["id"] },
          { foreignKeyName: "agent_knowledge_bases_knowledge_base_id_fkey"; columns: ["knowledge_base_id"]; referencedRelation: "knowledge_bases"; referencedColumns: ["id"] }
        ];
      };
      conversations: {
        Row: {
          id: string;
          agent_id: string;
          client_user_id: string | null;
          status: string | null;
          context: Json | null;
          started_at: string;
          last_activity_at: string;
          ended_at: string | null;
        };
        Insert: {
          id?: string;
          agent_id: string;
          client_user_id?: string | null;
          status?: string | null;
          context?: Json | null;
          started_at?: string;
          last_activity_at?: string;
          ended_at?: string | null;
        };
        Update: {
          id?: string;
          agent_id?: string;
          client_user_id?: string | null;
          status?: string | null;
          context?: Json | null;
          started_at?: string;
          last_activity_at?: string;
          ended_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "conversations_agent_id_fkey"; columns: ["agent_id"]; referencedRelation: "agents"; referencedColumns: ["id"] }
        ];
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender: string;
          content: string;
          audio_url: string | null;
          timestamp: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          sender: string;
          content: string;
          audio_url?: string | null;
          timestamp?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          sender?: string;
          content?: string;
          audio_url?: string | null;
          timestamp?: string;
        };
        Relationships: [
          { foreignKeyName: "messages_conversation_id_fkey"; columns: ["conversation_id"]; referencedRelation: "conversations"; referencedColumns: ["id"] }
        ];
      };
      dynamic_profiles: {
        Row: {
          id: string;
          agent_id: string;
          name: string;
          detection_rules: Json | null;
          profile_specific_prompt_addendum: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          agent_id: string;
          name: string;
          detection_rules?: Json | null;
          profile_specific_prompt_addendum?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          agent_id?: string;
          name?: string;
          detection_rules?: Json | null;
          profile_specific_prompt_addendum?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "dynamic_profiles_agent_id_fkey"; columns: ["agent_id"]; referencedRelation: "agents"; referencedColumns: ["id"] }
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      content_type_enum: "text" | "url" | "document" | "vector_id";
      conversation_status_enum: "active" | "ended" | "timeout";
      sender_enum: "user" | "agent";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];
